apiVersion: v1
Kind: ConfigMap
metadata:
    name: web-cm
    namespace: demo
data:
    upload-bucket: bd-airport-data
---
apiVersion: v1
Kind: Secret
metadata:
    name: aws-secrets-id
    namespace: demo
data:
    aws-access-key-id: WW91ciBhd3MgYWNjZXNzIGtleSBpZAo=
---
apiVersion: v1
Kind: Secret
metadata:
    name: aws-secrets-key
    namespace: demo
data:
    aws-secret-access-key: WW91ciBhd3MgYWNjZXNzIHNlY3JldCBrZXkK
